# Clock signal
set_property PACKAGE_PIN W5 [get_ports i_clock]							
	set_property IOSTANDARD LVCMOS33 [get_ports i_clock]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports i_clock]
 
# Switches
set_property PACKAGE_PIN V17 [get_ports {a[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[0]}]
set_property PACKAGE_PIN V16 [get_ports {i_sw_ex[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[1]}]
set_property PACKAGE_PIN W16 [get_ports {i_sw_ex[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[2]}]
set_property PACKAGE_PIN W17 [get_ports {i_sw_ex[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[3]}]
set_property PACKAGE_PIN W15 [get_ports {i_sw_ex[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[4]}]
set_property PACKAGE_PIN V15 [get_ports {i_sw_ex[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[5]}]
set_property PACKAGE_PIN W14 [get_ports {i_sw_ex[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[6]}]
set_property PACKAGE_PIN W13 [get_ports {i_sw_ex[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[7]}]
#set_property PACKAGE_PIN V2 [get_ports {i_sw_ex[8]}]					
	#set_property IOSTANDARD LVCMOS33 [get_ports {i_sw_ex[8]}]
 

# LEDs
set_property PACKAGE_PIN U16 [get_ports {out_alu[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[0]}]
set_property PACKAGE_PIN E19 [get_ports {out_alu[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[1]}]
set_property PACKAGE_PIN U19 [get_ports {out_alu[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[2]}]
set_property PACKAGE_PIN V19 [get_ports {out_alu[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[3]}]
set_property PACKAGE_PIN W18 [get_ports {out_alu[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[4]}]
set_property PACKAGE_PIN U15 [get_ports {out_alu[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[5]}]
set_property PACKAGE_PIN U14 [get_ports {out_alu[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[6]}]
set_property PACKAGE_PIN V14 [get_ports {out_alu[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[7]}]
#set_property PACKAGE_PIN V13 [get_ports {out_alu[8]}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {out_alu[8]}]



##Buttons enable
set_property PACKAGE_PIN U18 [get_ports i_btn_a_ex]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_btn_a_ex]
set_property PACKAGE_PIN T18 [get_ports i_btn_b_ex]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_btn_b_ex]
set_property PACKAGE_PIN W19 [get_ports i_btn_op_ex]						
	set_property IOSTANDARD LVCMOS33 [get_ports i_btn_op_ex]
